### ISSUE TITLE
USB Mass Storage to access SD card contents

### ISSUE THREAD

**Issue by parrottq** [CarletonURocketry/avionics-software#30]
#### Goal
The goal is to be able to access the contents off the SD card by connecting over USB to the board then to copy the contents out as a file. Ideally this would support Windows, MacOS and Linux.

#### Implementation

- [x] Adding mass storage device to existing USB driver
- [x] Implementing SCSI over USB
- [x] Implementing FAT32 file system
- [ ] Interfacing with SD card drivers

#### Reference

- [USB 2.0 Specification](http://sdphca.ucsd.edu/lab_equip_manuals/usb_20.pdf)
- [Seagate's SCSI Commands Reference Manual](https://www.seagate.com/files/staticfiles/support/docs/manual/Interface%20manuals/100293068j.pdf)
- [Oracle's SCSI Command Reference Guide](https://docs.oracle.com/en/storage/tape-storage/storagetek-sl150-modular-tape-library/slorm/scsi-reference-guide.pdf)
- [Mandatory commands by peripheral type](https://www.t10.org/lists/op-alph.txt)
- [USB Mass Storage Bulk-Only Transport](https://usb.org/sites/default/files/usbmassbulk_10.pdf) (Only needed to upgrade to SCSI)
- [USB Attached SCSI Protocol](https://web.archive.org/web/20120119200525/http://www.usb.org/developers/devclass_docs/uasp_1_0.zip) (zip)
- [Design of the FAT file system](https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system)
- [Understanding FAT32 Filesystems](https://www.pjrc.com/tech/8051/ide/fat32.html)
- [FAT32 reference](https://web.archive.org/web/20180826211450/read.pudn.com/downloads77/ebook/294884/FAT32%20Spec%20(SDA%20Contribution).pdf)

**Comment by parrottq** [comment]
These changes can be found [here](https://github.com/parrottq/avionics-software/tree/usb-mass-storage).

**Comment by lwei2** [comment]
How do I send SCSI instructions to a plugged USB device on a MacOS?

**Comment by lwei2** [comment]
这是来自QQ邮箱的假期自动回复邮件。谢谢您的来信，待我稍后查阅邮件，会第一时间给您回复，保持常联系。
