### ISSUE TITLE
Implement Driver for RFM69HCW 915 MHz Radio Module

### ISSUE THREAD

**Issue by samueldewan** [CarletonURocketry/avionics-software#6]
## Implement driver RFM69HCW 915 MHz Radio Module

Note: It is possible that this issue will be found to be unnecessary at some point in the future. We originally intended for these modules to be used for communication to the nose cone, but they may be replaced by a wired communications solution.

#### What Needs to be Done

The RFM69HCW is a radio module from Hope RF. It is essentially a breakout board for Semtech's  SX1231 transceiver IC which is controlled via an SPI interface.

We need a driver for the RFM69HCW radio module. The requirements for this driver are very similar to those of the RN2483 radio driver. The RFM69HCW driver needs to have:
- A descriptor structure which allows for multiple instances of the driver to be used
- An init function which allows for all of the configurable options of the radio module to be set
- A function which allows a buffer of data to be transmitted
- A function which allows for reception to be started in the background, the application code must be able to provide a callback function to be called when reception is complete
- The receive callback should be provided the RSSI value for the received packet as well as the data received data
- If possible it should be able to transmit while the radio is receiving, this will likely need to be implemented by canceling the ongoing reception and resuming after transmission is complete
- Support for controlling the RFM69HCW's GPIO pins though gpio.c

The driver will need to implement a state machine in order to manage communication with the radio module without blocking.

#### What has Been Done

No work has been done on this driver yet. A good place to look for some ideas on how to structure the driver code would be the existing RN2483 radio driver.

#### Reference Material

The RFM69HCW documentation is not great. I recommend looking at the documentation for the SX1231, which is the chip used on the RFM69HCW module.

RFM69HCW Documentation:

- [Data Sheet](https://www.hoperf.com/data/upload/portal/20190307/RFM69HCW-V1.1.pdf)
- [Product Page](https://www.hoperf.com/modules/rf_transceiver/RFM69HCW.html)
- [Arduino Driver](https://github.com/LowPowerLab/RFM69)

SX1231 Documentation:
- [Data Sheets and Resources](https://www.semtech.com/products/wireless-rf/fsk-transceivers/sx1231#download-resources)

#### Who is This For

The person who takes on this issue should be comfortable reading the documentation for the radio   and referencing other existing drivers in order to design a driver state machine.

#### Timeline

This task should be completed by the end of the Fall 2020 semester.

**Comment by arsalan0004** [comment]
This seems cool. I'd like to take it on.
